### ISSUE TITLE
ERROR Asset render failed: css/main.css

### ISSUE THREAD

**Issue by sheymann** [Linkurious/website#1]
![image](https://cloud.githubusercontent.com/assets/177962/22151106/d7ad7062-df1c-11e6-88ed-d96d45dbf24c.png)

> Error: File to import not found or unreadable: ../../../../bower_components/normalize-css/normalize
Parent style sheet: C:/Users/Seb/Documents/GitHub/website/themes/lktheme/source/css/main.scss
ERROR Asset render failed: css/main.css
Error: File to import not found or unreadable: ../../../../bower_components/normalize-css/normalize
Parent style sheet: C:/Users/Seb/Documents/GitHub/website/themes/lktheme/source/css/main.scss
    at Object.module.exports.renderSync (C:\Users\Seb\Documents\GitHub\website\node_modules\hexo-renderer-sass\node_modules\node-sass\lib\index.js:434:16)
    at Hexo.sassRenderer (C:\Users\Seb\Documents\GitHub\website\node_modules\hexo-renderer-sass\index.js:22:23)
    at C:\Users\Seb\Documents\GitHub\website\node_modules\hexo\lib\hexo\render.js:61:21
    at tryCatcher (C:\Users\Seb\Documents\GitHub\website\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Seb\Documents\GitHub\website\node_modules\hexo\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Seb\Documents\GitHub\website\node_modules\hexo\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Seb\Documents\GitHub\website\node_modules\hexo\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Seb\Documents\GitHub\website\node_modules\hexo\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Seb\Documents\GitHub\website\node_modules\hexo\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Seb\Documents\GitHub\website\node_modules\hexo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Seb\Documents\GitHub\website\node_modules\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

I've installed bower as a global dependency.

**Comment by TonyTR** [comment]
PA d'erreur chez moi .. tu as bien les sources Bower ?

**Comment by sheymann** [comment]
C'était un problème de git introuvable. Sacré Windows -_-.

**Comment by TonyTR** [comment]
Haha le Troll ;)

**Comment by sheymann** [comment]
C'est pénible, git est bien trouvé dans Powershell mais pas dans cmd.
